# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - src/SMD.IndentityServer4.Firestore/*

resources:
  containers:
  - container: firestore 
    image: mtlynch/firestore-emulator
    ports:
      - 8080:8080
    env:
      FIRESTORE_PROJECT_ID: 'project-id'
      PORT: '8080'

pool:
  vmImage: 'ubuntu-latest'

container: mcr.microsoft.com/dotnet/core/sdk:latest

services:
  firestore: firestore

variables:
  buildConfiguration: 'Release'
  major: '1'
  minor: '0'
  revision: $[counter(variables['minor'], 1)]
  nuget_version: '$(major).$(minor).$(revision)-dev'

steps:
- script: dotnet nuget add source "https://almarsumi.pkgs.visualstudio.com/_packaging/SMD/nuget/v3/index.json" --name "smd" --username "smd" --password "$(PAT)" --store-password-in-clear-text
- script: dotnet restore
  displayName: 'dotnet restore'

- task: DotNetCoreCLI@2
  displayName: 'build projects'
  inputs:
    command: 'build'
    projects: |
      src/SMD.IndentityServer4.Firestore/SMD.IndentityServer4.Firestore.csproj
      test/IdentityServer4.Firestore.IntegrationTests/IdentityServer4.Firestore.IntegrationTests.csproj
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'integration tests'
  inputs:
    command: 'test'
    projects: 'test/IdentityServer4.Firestore.IntegrationTests/IdentityServer4.Firestore.IntegrationTests.csproj'
    testRunTitle: 'integration tests'
  env:
    ProjectId: 'project-id'
    FIRESTORE_EMULATOR_HOST: 'firestore:8080'

- task: DotNetCoreCLI@2
  displayName: 'publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/SMD.IndentityServer4.Firestore/SMD.IndentityServer4.Firestore.csproj'

- task: DotNetCoreCLI@2
  displayName: 'pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/SMD.IndentityServer4.Firestore/SMD.IndentityServer4.Firestore.csproj'
    nobuild: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'nuget_version'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'